name: petvillage
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  animated_read_more_text: ^0.0.5
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.14.0
  country_picker: ^2.0.23
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.0
  flutter_stripe: ^10.0.0
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  google_fonts: ^6.1.0
  hive_flutter: ^1.1.0
  http: ^1.1.2
  intl: ^0.18.1
  logger: ^2.0.2+1
  lottie: ^2.7.0
  mailer: ^6.1.0
  marquee: ^2.2.3
  pay: ^1.1.2
  pinput: ^4.0.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  analyzer: ^6.2.0
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/petLogo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
